### ISSUE TITLE
Does it work on Rx590 with macOS 12?

### ISSUE THREAD

**Issue by byoungd** [iskakfatoni/ASUS_Z270_TUF_MARK1_SAPPHIRE_NITRO_RX580_6GB_HACKINTOSH_OPENCORE#1]
My pc is 
ASUS Z270-A
7700k
rx590

Does it work on Rx590 and macOS 12?

**Comment by iskakfatoni** [comment]
> My pc is ASUS Z270-A 7700k rx590
> 
> Does it work on Rx590 and macOS 12?

YES

**Comment by iskakfatoni** [comment]
I dont know, i dont have the device
